###
POST http://{{domain-address}}/matchs/chess
Content-Type: Application/JSON

{
  "userId": "4863d665-317c-48e2-957f-ffe5f5390da8"
}

###
POST http://{{domain-address}}/matchs/number
Content-Type: Application/JSON

{
  "userId": "4863d665-317c-48e2-957f-ffe5f5390da8"
}