###
POST http://{{domain-address}}/users/chess
Content-Type: application/json

{
 "name": "babo5"
}

###
POST http://{{domain-address}}/users/number
Content-Type: application/json

{
  "name": "babo5"
}